version: "3.5"

services:
  frontend:
    build:
      context: ./WebUI
      dockerfile: ./Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./WebUI/src:/app/src
    ports:
      - "5173:5173"

