version: "3.8"

services:
  frontend:
    build:
      context: ./WebUI
      dockerfile: ./Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./WebUI:/app
    ports:
      - "5173:5173"
    command: sh -c "cd /app && npm run dev"

