version: '3.8'

services:
  challenge1_challenge:
    build:
      context: ./server/challenge1/challenge
      dockerfile: Dockerfile
    image: challenge1/challenge

  challenge1_judge:
    build:
      context: ./server/challenge1/judge
      dockerfile: Dockerfile
    image: challenge1/judge

  challenge2_challenge:
    build:
      context: ./server/challenge2/challenge
      dockerfile: Dockerfile
    image: challenge2/challenge

  challenge2_judge:
    build:
      context: ./server/challenge2/judge
      dockerfile: Dockerfile
    image: challenge2/judge

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./server:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_ENV=development
    command: python -u app.py

  # client:
  #   build:
  #     context: ./client/WebUI
  #     dockerfile: ./Dockerfile
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   volumes:
  #     - ./WebUI:/app
  #   ports:
  #     - "5173:5173"
