version: '3.8'

services:
  challenge1_challenge:
    build:
      context: ./server/challenge1/challenge
      dockerfile: Dockerfile
    image: challenge1/challenge
    command: echo "Hello World"

  challenge1_judge:
    build:
      context: ./server/challenge1/judge
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: challenge1/judge
    command: echo "Hello World"

  challenge2_challenge:
    build:
      context: ./server/challenge2/challenge
      dockerfile: Dockerfile
    image: challenge2/challenge
    command: echo "Hello World"

  challenge2_judge:
    build:
      context: ./server/challenge2/judge
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: challenge2/judge
    command: echo "Hello World"

  challenge3_challenge:
    build:
      context: ./server/challenge3/challenge
      dockerfile: Dockerfile
    image: challenge3/challenge
    command: echo "Hello World"

  challenge3_judge:
    build:
      context: ./server/challenge3/judge
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: challenge3/judge
    command: echo "Hello World"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: inversity-provisioner-container
    container_name: inversity-provisioner-container
    ports:
      - '5000:5000'
    volumes:
      - ./server:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_ENV=development
    command: python -u app.py

  client:
    build:
      context: ./client/WebUI
      dockerfile: ./Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client/WebUI:/app
    ports:
      - "5173:5173"
    # command: sh -c "pwd && ls && cd /app && npm run dev:docker"
